// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PruebaECommerce.Repositories.Data;

#nullable disable

namespace PruebaECommerce.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260706044559_SeedInitialData")]
    partial class SeedInitialData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PruebaECommerce.Models.CartItemDbModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId");

                    b.ToTable("CartItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ProductId = 1,
                            Quantity = 1,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            ProductId = 2,
                            Quantity = 1,
                            UserId = 1
                        },
                        new
                        {
                            Id = 3,
                            ProductId = 3,
                            Quantity = 1,
                            UserId = 1
                        },
                        new
                        {
                            Id = 4,
                            ProductId = 4,
                            Quantity = 1,
                            UserId = 1
                        },
                        new
                        {
                            Id = 5,
                            ProductId = 5,
                            Quantity = 1,
                            UserId = 1
                        },
                        new
                        {
                            Id = 6,
                            ProductId = 6,
                            Quantity = 1,
                            UserId = 1
                        },
                        new
                        {
                            Id = 7,
                            ProductId = 7,
                            Quantity = 1,
                            UserId = 1
                        },
                        new
                        {
                            Id = 8,
                            ProductId = 8,
                            Quantity = 1,
                            UserId = 1
                        },
                        new
                        {
                            Id = 9,
                            ProductId = 9,
                            Quantity = 2,
                            UserId = 2
                        },
                        new
                        {
                            Id = 10,
                            ProductId = 10,
                            Quantity = 2,
                            UserId = 2
                        },
                        new
                        {
                            Id = 11,
                            ProductId = 11,
                            Quantity = 2,
                            UserId = 2
                        },
                        new
                        {
                            Id = 12,
                            ProductId = 12,
                            Quantity = 2,
                            UserId = 2
                        },
                        new
                        {
                            Id = 13,
                            ProductId = 13,
                            Quantity = 2,
                            UserId = 2
                        },
                        new
                        {
                            Id = 14,
                            ProductId = 14,
                            Quantity = 2,
                            UserId = 2
                        },
                        new
                        {
                            Id = 15,
                            ProductId = 15,
                            Quantity = 2,
                            UserId = 2
                        },
                        new
                        {
                            Id = 16,
                            ProductId = 16,
                            Quantity = 2,
                            UserId = 2
                        });
                });

            modelBuilder.Entity("PruebaECommerce.Models.OrderDbModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Discount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Subtotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Total")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Discount = 0.00m,
                            OrderDate = new DateTime(2026, 7, 5, 12, 0, 0, 0, DateTimeKind.Utc),
                            Subtotal = 500.00m,
                            Total = 500.50m,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            Discount = 0.00m,
                            OrderDate = new DateTime(2026, 7, 5, 12, 0, 0, 0, DateTimeKind.Utc),
                            Subtotal = 405.00m,
                            Total = 405.00m,
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            Discount = 0.00m,
                            OrderDate = new DateTime(2026, 7, 5, 12, 0, 0, 0, DateTimeKind.Utc),
                            Subtotal = 142.50m,
                            Total = 142.50m,
                            UserId = 1
                        },
                        new
                        {
                            Id = 4,
                            Discount = 0.00m,
                            OrderDate = new DateTime(2026, 7, 5, 12, 0, 0, 0, DateTimeKind.Utc),
                            Subtotal = 303.00m,
                            Total = 303.00m,
                            UserId = 1
                        },
                        new
                        {
                            Id = 5,
                            Discount = 0.00m,
                            OrderDate = new DateTime(2026, 7, 5, 12, 0, 0, 0, DateTimeKind.Utc),
                            Subtotal = 825.00m,
                            Total = 825.00m,
                            UserId = 2
                        });
                });

            modelBuilder.Entity("PruebaECommerce.Models.OrderDetailDbModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderDetails");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            OrderId = 1,
                            ProductId = 1,
                            Quantity = 1,
                            UnitPrice = 50.00m
                        },
                        new
                        {
                            Id = 2,
                            OrderId = 1,
                            ProductId = 2,
                            Quantity = 1,
                            UnitPrice = 50.00m
                        },
                        new
                        {
                            Id = 3,
                            OrderId = 1,
                            ProductId = 3,
                            Quantity = 1,
                            UnitPrice = 50.00m
                        },
                        new
                        {
                            Id = 4,
                            OrderId = 1,
                            ProductId = 4,
                            Quantity = 1,
                            UnitPrice = 50.00m
                        },
                        new
                        {
                            Id = 5,
                            OrderId = 2,
                            ProductId = 5,
                            Quantity = 1,
                            UnitPrice = 50.00m
                        },
                        new
                        {
                            Id = 6,
                            OrderId = 2,
                            ProductId = 6,
                            Quantity = 1,
                            UnitPrice = 50.00m
                        },
                        new
                        {
                            Id = 7,
                            OrderId = 2,
                            ProductId = 7,
                            Quantity = 1,
                            UnitPrice = 50.00m
                        },
                        new
                        {
                            Id = 8,
                            OrderId = 2,
                            ProductId = 8,
                            Quantity = 1,
                            UnitPrice = 50.00m
                        },
                        new
                        {
                            Id = 9,
                            OrderId = 3,
                            ProductId = 9,
                            Quantity = 1,
                            UnitPrice = 50.00m
                        },
                        new
                        {
                            Id = 10,
                            OrderId = 3,
                            ProductId = 10,
                            Quantity = 1,
                            UnitPrice = 50.00m
                        },
                        new
                        {
                            Id = 11,
                            OrderId = 3,
                            ProductId = 11,
                            Quantity = 1,
                            UnitPrice = 50.00m
                        },
                        new
                        {
                            Id = 12,
                            OrderId = 3,
                            ProductId = 12,
                            Quantity = 1,
                            UnitPrice = 50.00m
                        },
                        new
                        {
                            Id = 13,
                            OrderId = 4,
                            ProductId = 13,
                            Quantity = 1,
                            UnitPrice = 50.00m
                        },
                        new
                        {
                            Id = 14,
                            OrderId = 4,
                            ProductId = 14,
                            Quantity = 1,
                            UnitPrice = 50.00m
                        },
                        new
                        {
                            Id = 15,
                            OrderId = 4,
                            ProductId = 15,
                            Quantity = 1,
                            UnitPrice = 50.00m
                        },
                        new
                        {
                            Id = 16,
                            OrderId = 4,
                            ProductId = 16,
                            Quantity = 1,
                            UnitPrice = 50.00m
                        },
                        new
                        {
                            Id = 17,
                            OrderId = 5,
                            ProductId = 17,
                            Quantity = 1,
                            UnitPrice = 50.00m
                        },
                        new
                        {
                            Id = 18,
                            OrderId = 5,
                            ProductId = 18,
                            Quantity = 1,
                            UnitPrice = 50.00m
                        },
                        new
                        {
                            Id = 19,
                            OrderId = 5,
                            ProductId = 19,
                            Quantity = 1,
                            UnitPrice = 50.00m
                        },
                        new
                        {
                            Id = 20,
                            OrderId = 5,
                            ProductId = 20,
                            Quantity = 1,
                            UnitPrice = 50.00m
                        });
                });

            modelBuilder.Entity("PruebaECommerce.Models.ProductDbModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Tecnología",
                            Code = "TECH-001",
                            Name = "Monitor 27'' 144Hz",
                            Price = 250.00m,
                            Stock = 15
                        },
                        new
                        {
                            Id = 2,
                            Category = "Tecnología",
                            Code = "TECH-002",
                            Name = "Teclado Mecánico",
                            Price = 85.50m,
                            Stock = 30
                        },
                        new
                        {
                            Id = 3,
                            Category = "Tecnología",
                            Code = "TECH-003",
                            Name = "Mouse Inalámbrico",
                            Price = 45.00m,
                            Stock = 50
                        },
                        new
                        {
                            Id = 4,
                            Category = "Tecnología",
                            Code = "TECH-004",
                            Name = "Laptop Core i7",
                            Price = 1200.00m,
                            Stock = 10
                        },
                        new
                        {
                            Id = 5,
                            Category = "Tecnología",
                            Code = "TECH-005",
                            Name = "Auriculares Noise Cancelling",
                            Price = 150.00m,
                            Stock = 20
                        },
                        new
                        {
                            Id = 6,
                            Category = "Oficina",
                            Code = "TECH-006",
                            Name = "Silla Ergonómica",
                            Price = 199.99m,
                            Stock = 12
                        },
                        new
                        {
                            Id = 7,
                            Category = "Oficina",
                            Code = "TECH-007",
                            Name = "Escritorio Ajustable",
                            Price = 350.00m,
                            Stock = 8
                        },
                        new
                        {
                            Id = 8,
                            Category = "Tecnología",
                            Code = "TECH-008",
                            Name = "Webcam 4K",
                            Price = 90.00m,
                            Stock = 25
                        },
                        new
                        {
                            Id = 9,
                            Category = "Tecnología",
                            Code = "TECH-009",
                            Name = "Micrófono USB",
                            Price = 60.00m,
                            Stock = 40
                        },
                        new
                        {
                            Id = 10,
                            Category = "Tecnología",
                            Code = "TECH-010",
                            Name = "Docking Station",
                            Price = 110.00m,
                            Stock = 15
                        },
                        new
                        {
                            Id = 11,
                            Category = "Deportes",
                            Code = "GYM-001",
                            Name = "Mancuernas Ajustables 24kg",
                            Price = 180.00m,
                            Stock = 20
                        },
                        new
                        {
                            Id = 12,
                            Category = "Suplementos",
                            Code = "GYM-002",
                            Name = "Proteína Whey 2lbs",
                            Price = 35.00m,
                            Stock = 100
                        },
                        new
                        {
                            Id = 13,
                            Category = "Suplementos",
                            Code = "GYM-003",
                            Name = "Creatina Monohidratada",
                            Price = 25.00m,
                            Stock = 80
                        },
                        new
                        {
                            Id = 14,
                            Category = "Suplementos",
                            Code = "GYM-004",
                            Name = "Pre-entreno",
                            Price = 30.00m,
                            Stock = 60
                        },
                        new
                        {
                            Id = 15,
                            Category = "Deportes",
                            Code = "GYM-005",
                            Name = "Cinturón de Levantamiento",
                            Price = 40.00m,
                            Stock = 30
                        },
                        new
                        {
                            Id = 16,
                            Category = "Deportes",
                            Code = "GYM-006",
                            Name = "Rodilleras Neopreno",
                            Price = 22.50m,
                            Stock = 45
                        },
                        new
                        {
                            Id = 17,
                            Category = "Deportes",
                            Code = "GYM-007",
                            Name = "Zapatillas Training",
                            Price = 95.00m,
                            Stock = 25
                        },
                        new
                        {
                            Id = 18,
                            Category = "Ropa",
                            Code = "GYM-008",
                            Name = "Camiseta Dry-Fit",
                            Price = 18.00m,
                            Stock = 150
                        },
                        new
                        {
                            Id = 19,
                            Category = "Accesorios",
                            Code = "GYM-009",
                            Name = "Botella de Agua Acero 1L",
                            Price = 15.00m,
                            Stock = 200
                        },
                        new
                        {
                            Id = 20,
                            Category = "Accesorios",
                            Code = "GYM-010",
                            Name = "Toalla Microfibra",
                            Price = 8.50m,
                            Stock = 300
                        });
                });

            modelBuilder.Entity("PruebaECommerce.Models.UserDbModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "admin@testecommerce.com",
                            Password = "Abc123"
                        },
                        new
                        {
                            Id = 2,
                            Email = "usuario@testecommerce.com",
                            Password = "Abc123"
                        });
                });

            modelBuilder.Entity("PruebaECommerce.Models.CartItemDbModel", b =>
                {
                    b.HasOne("PruebaECommerce.Models.ProductDbModel", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PruebaECommerce.Models.UserDbModel", "User")
                        .WithMany("CartItems")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PruebaECommerce.Models.OrderDbModel", b =>
                {
                    b.HasOne("PruebaECommerce.Models.UserDbModel", "User")
                        .WithMany("OrderItems")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("PruebaECommerce.Models.OrderDetailDbModel", b =>
                {
                    b.HasOne("PruebaECommerce.Models.OrderDbModel", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PruebaECommerce.Models.ProductDbModel", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("PruebaECommerce.Models.OrderDbModel", b =>
                {
                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("PruebaECommerce.Models.UserDbModel", b =>
                {
                    b.Navigation("CartItems");

                    b.Navigation("OrderItems");
                });
#pragma warning restore 612, 618
        }
    }
}
